#!/bin/zsh

local    opt arg
local    flag
local    flag2="(F)"
local    modifier=":a"
local    printer="echo"
local    pipe="cat"
local -a args
local    this="${${(%):-%N}:A:h}"

getopts() {
    printf -- "%s\n" $argv | sed -E '
    s/^-([A-Za-z]+)/- \1 /
    s/^--([A-Za-z0-9_-]+)(!?)=?(.*)/-- \1 \3 \2 /' \
        | awk -f "$this/src/share/getopts.awk"
}

getopts "$argv[@]" \
    | while read opt arg
    do
        case $opt in
            t|tilda)
                flag="(D)"
                ;;
            f|follow-link)
                modifier=":A"
                ;;
            o|oneline)
                flag2=""
                ;;
            _)
                args+=("$arg")
                ;;
            *)
                printf "$opt: unknown option\n" >&2
                exit 1
        esac
    done

eval '$printer ${'$flag2'${'$flag'${args[@]}'$modifier'}}' \
    | (tee /dev/fd/3 | tr -d "\n" | pbcopy) 3>&1
unfunction getopts
